PPPK/PPPK/Models/RouteInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PPPK.Models
{
    [Table("RouteInfo")]
    public class RouteInfo
    {
        [Key]
        public int IDRouteInfo { get; set; }
        [Required]
        public DateTime? DateTimeStart { get; set; }

        [Required]
        public DateTime? DateTimeEnd { get; set; }
        public double? LatitudeStart { get; set; }
        public double? LongitudeStart { get; set; }
        public double? LatitudeEnd { get; set; }
        public double? LongitudeEnd { get; set; }
        public double? DistanceInKm { get; set; }
        public double? AverageSpeed { get; set; }
        public double? FuelExpense { get; set; }
        public int? TravelOrderID { get; set; }
        [ForeignKey("TravelOrderID")]
        public virtual TravelOrder TravelOrder { get; set; }
    }
}

PPPK/PPPK/Controllers/DataSetController.cs
using PPPK.Models;
using PPPK.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPPK.Controllers
{
    public class DataSetController : Controller
    {
        private readonly DataSetService service;
        private readonly XmlService xmlService;
        public DataSetController()
        {
            service = new DataSetService();
            xmlService = new XmlService();
            //service.ExportToXml();
        }

        // GET: DataSet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ImportRouteInfo()
        {
            var success = service.ImportFromXml();
            var message = success ? "Data sucessfuly imported" : "Import failed";
            return Json(new { success, message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreateBackup()
        {
            var success = xmlService.CreateBackup();
            var message = success ? "Backup sucessfuly created" : "Backup failed to create";
            return Json(new { success, message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ClearDatabase()
        {
            var success = xmlService.ClearDatabase();
            var message = success ? "Database sucessfuly cleared" : "Database failed to clear";
            return Json(new { success, message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RestoreBackup()
        {
            var success = xmlService.ImportBackup();
            var message = success ? "Database sucessfuly restored" : "Database failed to restore";
            return Json(new { success, message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTravelOrders()
        {
            var travelOrders = service.GetTravelOrders();
            return Json(new { data = travelOrders }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRoutesForTravelOrder(int id)
        {
            var routes = service.GetRouteInfoesForTravelOrder(id);
            ViewBag.TravelOrderID = id;
            return PartialView("_RouteInfoes", routes);
        }

        public ActionResult GetRouteInfoForm(int? id)
        {
            var model = service.GetRouteInfo(id);
            return PartialView("_RouteInfoForm", model);
        }

        [HttpPost]
        public ActionResult InsertRouteInfo(RouteInfo model)
        {
            if (ModelState.IsValid)
            {
                return Json(new { success = service.InsertRouteInfo(model) });
            }
            return Json(new { success = false, errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList() });
        }

        [HttpPatch]
        public ActionResult UpdateRouteInfo(RouteInfo model)
        {
            if (ModelState.IsValid)
            {
                return Json(new { success = service.UpdateRouteInfo(model) });
            }
            return Json(new { success = false, errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList() });
        }

        [HttpDelete]
        public ActionResult DeleteRouteInfo(int id)
        {
            return Json(new { success = service.DeleteRouteInfo(id) });
        }

    }
}

PPPK/PPPK/Views/DataSet/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>DataSet</h2>

<h4>Import Route info</h4>

<div>
    <button id="btnImportRI" class="btn bnt-primary">Import route info</button>
</div>

<h4>Xml</h4>
<div>
    <button id="btnBackup" class="btn btn-info">Backup database</button>
    <button id="btnClear" class="btn btn-warning">Clear database</button>
    <button id="btnRestore" class="btn btn-success">Restore database</button>
</div>

<!-- Modal -->
<div id="modal-form" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body container" style="overflow:hidden; width:100%;">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="">
            <table class="table table-condensed table-hover" id="travel-order-table" style="width:100%">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Driver</th>
                        <th>Vehicle</th>
                        <th>Type</th>
                        <th>Expected number of days</th>
                        <th>Reason for travel</th>
                        <th>Start city</th>
                        <th>End city</th>
                        <th>Document Date</th>
                        <th>Total cost</th>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot></tfoot>
            </table>
        </div>
        <div class="" id="routes">
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $('#btnBackup').on('click', e => {
            makeRestoreBackupAjax('@Url.Action("CreateBackup", "DataSet")');
        });

        $('#btnClear').on('click', e => {
            alertify.confirm(
                "Clear",
                "Are you sure you want to clear database?",
                () => makeRestoreBackupAjax('@Url.Action("ClearDatabase", "DataSet")'),
                () => { }
            );
        });

        $('#btnRestore').on('click', e => {
            makeRestoreBackupAjax('@Url.Action("RestoreBackup", "DataSet")');
        });

        $('#btnImportRI').on('click', e => {
            makeRestoreBackupAjax('@Url.Action("ImportRouteInfo", "DataSet")');
        });


    const travelOrderColumns = [
        { "data": "IDTravelOrder" },
        { "data": "DriverID" },
        { "data": "VehicleID" },
        { "data": "TravelOrderTypeID" },
        { "data": "ExpectedNumberOfDays" },
        { "data": "ReasonForTravel" },
        { "data": "CityStartId" },
        { "data": "CityEndId" },
        {
            "data": "DocumentDate",
            render: function (data, type, full, meta) {
                return getHtmlDateForDataTable(data);
            }
        },
        { "data": "TotalCost" },
    ];

    const table = $('#travel-order-table').DataTable({
            scrollX: true,
            deferRender: true,
            autoWidth: true,
            select: true,
            bLengthChange: false,
            bFilter: false,
            bInfo: false,
            ajax: {
                url: '@Url.Action("GetTravelOrders","DataSet")',
                method: 'GET'
            },
            columns: travelOrderColumns,
            columnDefs: [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": false
                }
            ],
        });

        $('#travel-order-table').DataTable().on('select', function (e, dt, type, indexes) {
            reloadTable();
        });

        $('#travel-order-table').DataTable().on('deselect', function (e, dt, type, indexes) {
            $('#routes').html('');
        });

        function regiseterOnClickListeners() {
            $('#btnCreate').on('click', function (e) {
                showInsertForm(
                    '@Url.Action("GetRouteInfoForm","DataSet")',
                    '@Url.Action("InsertRouteInfo","DataSet")',
                    reloadTable,
                    () => $('#travelOrderID').val($(this).siblings('input:hidden').val())
                );
            });

            $('.btnEdit').on('click', function (e) {
                const id = $(this).siblings('input:hidden').val();
                showUpdateForm('@Url.Action("GetRouteInfoForm","DataSet")', id,'@Url.Action("UpdateRouteInfo","DataSet")', reloadTable);
            });

            $('.btnDelete').on('click', function (e) {
                const id = $(this).siblings('input:hidden').val();
                deleteEntity('@Url.Action("DeleteRouteInfo","DataSet")', id, reloadTable)
            });

        }

        function reloadTable() {
            const id = getSelectedItemId( $('#travel-order-table').DataTable() );
            if (id != -1) {
                $.ajax({
                    url: '@Url.Action("GetRoutesForTravelOrder", "DataSet")',
                    data: { id: id },
                    dataType: 'html',
                    success: function (response) {
                        $('#routes').html(response);
                        regiseterOnClickListeners();
                    }
                });
            } else {
                $('#routes').html('');
            }
        }

        function makeRestoreBackupAjax(url) {
            $.ajax({
                method:'get',
                url: url,
                dataType:'json',
                success: (response) => {
                    setAlertifyConfig();
                    if (response.success) {
                        alertify.success(response.message);
                        $('#travel-order-table').DataTable().ajax.reload();
                    } else {
                        alertify.error(response.message);
                    }
                }
            });
        }
    </script>
}

PPPK/PPPK/Views/DataSet/_RouteInfoForm.cshtml
@model PPPK.Models.RouteInfo

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RouteInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDRouteInfo)
        @Html.HiddenFor(model => model.TravelOrderID, new { id = "travelOrderID" })

        <div class="form-group">
            @Html.LabelFor(model => model.DateTimeStart, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DateTimeStart)
                @Html.ValidationMessageFor(model => model.DateTimeStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTimeEnd, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DateTimeEnd)
                @Html.ValidationMessageFor(model => model.DateTimeEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LatitudeStart, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.LatitudeStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LatitudeStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongitudeStart, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.LongitudeStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongitudeStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LatitudeEnd, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.LatitudeEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LatitudeEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongitudeEnd, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.LongitudeEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongitudeEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistanceInKm, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DistanceInKm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DistanceInKm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AverageSpeed, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.AverageSpeed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AverageSpeed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FuelExpense, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.FuelExpense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FuelExpense, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

PPPK/PPPK/Views/DataSet/_RouteInfoes.cshtml
@model IEnumerable<PPPK.Models.RouteInfo>

<p>
    <input type="hidden" value="@ViewBag.TravelOrderID" name="VehicleID" />
    <button class="btn btn-default" id="btnCreate">Create New</button>
</p>
@if (Model.Count() > 0)
{
    <div class="table-responsive">
        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DateTimeStart)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateTimeEnd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LatitudeStart)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LongitudeStart)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LatitudeEnd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LongitudeEnd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DistanceInKm)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AverageSpeed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FuelExpense)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TravelOrderID)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTimeStart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTimeEnd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LatitudeStart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LongitudeStart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LatitudeEnd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LongitudeEnd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DistanceInKm)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AverageSpeed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FuelExpense)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TravelOrderID)
                    </td>
                    <td style="white-space:nowrap">
                        @Html.HiddenFor(m => item.IDRouteInfo)
                        <a href="#" onclick="javascript:return false;" class="btnEdit">Edit</a> |
                        <a href="#" onclick="javascript:return false;" class="btnDelete">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
}